# Generated by Django 4.2.2 on 2023-07-08 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sku', models.IntegerField(blank=True, default=None, null=True)),
                ('Name', models.CharField(max_length=150)),
                ('Number', models.IntegerField(blank=True, default=None, null=True)),
                ('Door', models.CharField(max_length=150)),
                ('Address', models.CharField(max_length=150)),
                ('City', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='contacted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=150)),
                ('Mail', models.CharField(default='', max_length=150)),
                ('Select', models.CharField(choices=[('Enquiry', 'ENQUIRY'), ('Services', 'SERVICES'), ('Quality Base', 'QUALITY BASE')], default='1', max_length=20)),
                ('Contact', models.IntegerField(default='')),
                ('Message', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='cycles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('show', models.CharField(max_length=20)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=store.models.getFileName)),
                ('sku', models.IntegerField()),
                ('chase', models.CharField(default='', max_length=150)),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qty', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cycles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
